### To check if api is up and running (make sur the port number is right)
GET http://localhost:4242/
content-type: application/json

### To add a new question
GET http://localhost:4242/api/
content-type: application/json


### To add a new question
POST http://localhost:4242/api/
content-type: application/json

{
  "text": "How much would you charge for washing all the windows in this city?"
}